### ISSUE TITLE
(suggestion if you do end up using it) Avaritia Singularities 

### ISSUE THREAD

**Issue by Zer0Lyfe** [Vyraal1/Interaction#27]
This Mod: https://minecraft.curseforge.com/projects/singularities
Allows you to create custom singularities easily unless you just use the Extended Crafting singularities.

**Comment by Vyraal1** [comment]
Thanks for the suggestion, it was on my radar since I usually follow any mods that Shadows puts out, the only issue atm is that the last time I checked it out there really wasn't a GUI for the compressor, however it was pretty neat that the items needed to be dropped in world - which could probably take a while as the fastest item dropper I know is the Botania Open Crate.

At the moment we're still far from deciding if we even need anymore singularities than the ones currently offered.

**Comment by Zer0Lyfe** [comment]
you can out right disable the compressor as well and just use the Avaritia Compressor one if you want as well.
