### ISSUE TITLE
[0.09] Minor issues

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#31]
1. Empty recipe for AE2 charger defined in AppliedEnergistics2+Addons.zs. This results in a charger being in the output of a crafting table every time you open one up.

2. Very long processing times for the 3 alloy kiln recipes (bronze and brass from dusts, refined iron ingots) added in Immersive.zs. Standard time seems to be more like 200 ticks, not 1200. This also increases fuel use significantly. Ignore if this is intended behaviour.

**Comment by Hjaldar** [comment]
3. Refined Iron Plates (for Miniaturization Field Projector) not craftable before steel is available. I fixed this by adding:
`global plateRefinedIron  as IItemStack = <contenttweaker:material_part:194>;`
and
`global ingotRefinedIron as IItemStack = <techreborn:ingot:19>;`
to Global.zs and
```
   #Refined Iron Plates
makeHammerPlate(plateRefinedIron, <ore:ingotRefinedIron>);
makeSqueezerPlateRecipe(plateRefinedIron, ingotRefinedIron);
```
to Microcrafting.zs

**Comment by Vyraal1** [comment]
1) Fixed in-dev, whoopsies daisies.
2) Impure dusts are supposed to take a long time, in fact I'm not sure if I want to keep all of the other alloy recipes at the same speed as well. This was really intended to have the player make at least 2-3 Alloy Kilns, and before switching to rf based counterparts. Alloy Tiering is probably going to be Alloy Kiln -> TR Alloy Smelter -> Arc Furnace -> either Item Compound maker or an MM blast furnace.
3) Implemented your fix, good watching out.
