### ISSUE TITLE
Enchantments with similar effects / Too many enchantments?

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#58]
1. There are multiple mods adding similar enchantments, e.g.

-  Life Steal (Silent's Gems), Life Steal (Armor Plus), Life Stealing (Evilcraft), Leech (COFH Core), Life Leech (Cyclic)
-  Smelting (Astral Sorcery), Smelting (CoFH Core), Autosmelt (Cyclic)
-  Multishot (Cyclic), Multishot (CoFH Core)
-  Insight (CoFH Core), XP Boost (Cyclic)

Should we remove some of these? Should we reduce to one per category where possible? If so, do people have preferences as to which should be kept? The only mod I am aware of (so far) that doesn't allow disabling its enchants is Armor Plus.

2. Many enchants makes enchanting potentially time-consuming and expensive. This may be good or bad. Discuss.

**Comment by Vyraal1** [comment]
I'm inclined to remove the truly redundant enchantments such as the Smelting variants from CoFHCore / Astral Sorcery / Autosmelt since they don't stack.

The other issue is whether or not to remove the XP Boost/ Lifesteal enchantments that DO stack. I personally always found it pretty fun making uber strong swords that have enchantments piled on them all the time (eg. Wrath V, Sharpness V, etc.).

I think that the vanilla enchanting method does suffer a bit more due to RNG because of the added enchantments, but that also offers us to create progression opportunities for each enchantment token. In the same way players could add modifiers to TiCon tools via different materials, they can also add different modifiers/enchantments by crafting the enchantment tokens (assuming we could get them to work god damn it).

**Comment by Hjaldar** [comment]
All enchantments on version 0.13 as a reference.

[enchantments_2018-02-21_18.46.05.txt](https://github.com/Vyraal1/Interaction/files/1743199/enchantments_2018-02-21_18.46.05.txt)

**Comment by Hjaldar** [comment]
Action taken so far in https://github.com/Vyraal1/Interaction/pull/59

- Disable Magnet (Cyclic) in favour of Magnetic (Random Things)
- Disable AutoSmelt (Cyclic) in favour of Smelting (CoFH Core) and Scorching Heat (Astral Sorcery - very rare)
- Disable Excavation (Cyclic) in favour of OreExcavation (OEIntegration)
- Disable Multi-Shot (Cyclic) in favour of Multishot (CoFH Core)

I also tested stacking all of the Life Steal/Leech enchants on a 15 damage sword. Between the first hit and the killing blow it returned about 10 hearts to the player. So it is OP but not broken OP.

**Comment by Hjaldar** [comment]
Changes so far will be in v0.15 (or whatever comes after 0.14).

**Comment by Vyraal1** [comment]
Merged in
